# Generated by Django 3.2.8 on 2022-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220820_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='introduct',
            field=models.CharField(default='这个人很懒，不会写简介！', max_length=255, verbose_name='简介'),
        ),
    ]
