# Generated by Django 3.2.8 on 2022-09-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220830_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='subscribe',
        ),
    ]
