# Generated by Django 3.2.8 on 2022-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('camera_username', models.CharField(max_length=64, verbose_name='摄像头用户名')),
                ('camera_password', models.CharField(max_length=64, verbose_name='摄像头密码')),
                ('camera_ip', models.CharField(max_length=64, verbose_name='设备IP')),
                ('camera_port', models.IntegerField(verbose_name='设备端口')),
                ('live_photo', models.FileField(upload_to='streaming_photo/', verbose_name='封面图')),
                ('live_title', models.CharField(max_length=32, verbose_name='直播标题')),
                ('live_desc', models.CharField(max_length=64, verbose_name='直播描述')),
            ],
            options={
                'verbose_name': '直播管理',
                'db_table': 'livestreaming',
            },
        ),
    ]
