# Generated by Django 3.2.8 on 2022-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestreaming',
            name='camera_ip',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备IP'),
        ),
        migrations.AlterField(
            model_name='livestreaming',
            name='camera_password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='摄像头密码'),
        ),
        migrations.AlterField(
            model_name='livestreaming',
            name='camera_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='设备端口'),
        ),
        migrations.AlterField(
            model_name='livestreaming',
            name='camera_username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='摄像头用户名'),
        ),
    ]
