# Generated by Django 3.2.8 on 2022-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestreaming', '0002_auto_20220904_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestreaming',
            name='live_photo',
            field=models.FileField(upload_to='static/streaming_photo/', verbose_name='封面图'),
        ),
    ]
