# Generated by Django 3.2.8 on 2022-08-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='视频分组')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('file', models.FileField(max_length=255, upload_to='', verbose_name='视频文件')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面图片')),
                ('status', models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True, verbose_name='发布状态')),
                ('video_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videolist.classification', verbose_name='视频类')),
            ],
            options={
                'db_table': 'video',
            },
        ),
    ]
