# Generated by Django 3.2.8 on 2022-08-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220820_2329'),
        ('videolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='users_collection',
            field=models.ManyToManyField(related_name='collected_video', to='users.Users', verbose_name='收藏'),
        ),
        migrations.AddField(
            model_name='video',
            name='users_favorite',
            field=models.ManyToManyField(related_name='favorite_video', to='users.Users', verbose_name='喜欢'),
        ),
        migrations.AddField(
            model_name='video',
            name='users_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='video',
            name='users_view_count',
            field=models.IntegerField(default=0, verbose_name='观看次数'),
        ),
    ]
