# Generated by Django 3.2.8 on 2022-08-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220820_2329'),
        ('videolist', '0002_auto_20220827_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to='', verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='users_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户'),
        ),
    ]
