# Generated by Django 3.2.8 on 2022-08-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220820_2329'),
        ('videolist', '0003_auto_20220827_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.CharField(blank=True, default='暂无', max_length=1000, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='用户外键')),
                ('video_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videolist.video', verbose_name='视频外键')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
