# Generated by Django 3.2.8 on 2022-09-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0004_auto_20220828_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='封面图片'),
        ),
    ]
