# Generated by Django 3.2.8 on 2022-09-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0005_alter_video_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('0', '发布中'), ('1', '未发布')], default=0, max_length=1, verbose_name='发布状态'),
        ),
    ]
