# Generated by Django 3.2.8 on 2022-09-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0006_alter_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(max_length=2000, null=True, upload_to='', verbose_name='视频文件'),
        ),
    ]
