# Generated by Django 3.2.8 on 2022-09-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0007_auto_20220901_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': '视频分类管理'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论管理'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频管理'},
        ),
    ]
