# Generated by Django 3.2.8 on 2022-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_avatar'),
        ('videolist', '0008_auto_20220904_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='users_collection',
            field=models.ManyToManyField(blank=True, null=True, related_name='collected_video', to='users.Users', verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='video',
            name='users_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_video', to='users.Users', verbose_name='喜欢'),
        ),
    ]
